///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CharacterModel {
/*
{
  "char_id": 1,
  "name": "Walter White",
  "birthday": "09-07-1958",
  "occupation": [
    "High School Chemistry Teacher"
  ],
  "img": "https://images.amcnetworks.com/amc.com/wp-content/uploads/2015/04/cast_bb_700x1000_walter-white-lg.jpg",
  "status": "Presumed dead",
  "nickname": "Heisenberg",
  "appearance": [
    1
  ],
  "portrayed": "Bryan Cranston",
  "category": "Breaking Bad",
  "better_call_saul_appearance": [
    1
  ]
}
*/

  int? charId;
  String? name;
  String? birthday;
  List<String?>? occupation;
  String? img;
  String? status;
  String? nickname;
  List<int?>? appearance;
  String? portrayed;
  String? category;
  List<int?>? betterCallSaulAppearance;

  CharacterModel({
    this.charId,
    this.name,
    this.birthday,
    this.occupation,
    this.img,
    this.status,
    this.nickname,
    this.appearance,
    this.portrayed,
    this.category,
    this.betterCallSaulAppearance,
  });
  CharacterModel.fromJson(Map<String, dynamic> json) {
    charId = json["char_id"]?.toInt();
    name = json["name"]?.toString();
    birthday = json["birthday"]?.toString();
    if (json["occupation"] != null) {
      final v = json["occupation"];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      occupation = arr0;
    }
    img = json["img"]?.toString();
    status = json["status"]?.toString();
    nickname = json["nickname"]?.toString();
    if (json["appearance"] != null) {
      final v = json["appearance"];
      final arr0 = <int>[];
      v.forEach((v) {
        arr0.add(v.toInt());
      });
      appearance = arr0;
    }
    portrayed = json["portrayed"]?.toString();
    category = json["category"]?.toString();
    if (json["better_call_saul_appearance"] != null) {
      final v = json["better_call_saul_appearance"];
      final arr0 = <int>[];
      v.forEach((v) {
        arr0.add(v.toInt());
      });
      betterCallSaulAppearance = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["char_id"] = charId;
    data["name"] = name;
    data["birthday"] = birthday;
    if (occupation != null) {
      final v = occupation;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data["occupation"] = arr0;
    }
    data["img"] = img;
    data["status"] = status;
    data["nickname"] = nickname;
    if (appearance != null) {
      final v = appearance;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data["appearance"] = arr0;
    }
    data["portrayed"] = portrayed;
    data["category"] = category;
    if (betterCallSaulAppearance != null) {
      final v = betterCallSaulAppearance;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data["better_call_saul_appearance"] = arr0;
    }
    return data;
  }
}
